// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadNovel(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadNovel'](arg1, arg2, arg3);
}

export function GetTitle(arg1) {
  return window['go']['main']['App']['GetTitle'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScrapeChapter(arg1) {
  return window['go']['main']['App']['ScrapeChapter'](arg1);
}

export function ScrapeChapterWithHTML(arg1) {
  return window['go']['main']['App']['ScrapeChapterWithHTML'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function StartScraping(arg1) {
  return window['go']['main']['App']['StartScraping'](arg1);
}
