// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadNovel(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function GetTitle(arg1:string):Promise<string>;

export function LoadSettings():Promise<main.Settings>;

export function OpenFolder(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ScrapeChapter(arg1:string):Promise<string>;

export function ScrapeChapterWithHTML(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function StartScraping(arg1:string):Promise<main.ScrapeResult>;
